### ISSUE TITLE
p5.js mode

### ISSUE THREAD

**Issue by ethilise** [cdaein/ssam#7]
Hi, not really an issue here:
Is there a way to use p5.js with ssam? This doesn't seem to work: [P5 Mode](https://github.com/cdaein/ssam/blob/main/docs/mode-p5.md)

Cheers

**Comment by cdaein** [comment]
Hi,
p5 works differently than most other canvas libraries, so I haven't got a chance to integrate it yet.
I cannot promise if or when it will be done as I don't use p5js much personally and with my limited time and resource, I can only focus on the things that I use most often.
Sorry about the confusion! I will edit the doc to be more clear.
Please refer to the [Wiki](https://github.com/cdaein/ssam/wiki) for currently supported features.

**Comment by ethilise** [comment]
Thank you!
